name: Test with Jest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: make deploy

    - name: Run tests
      run: make test
      env: # Or as an environment variable
        PARCEL_WORKERS: 3
        SESSION_KEY: ${{ secrets.SESSION_KEY }}
        PORT: ${{ secrets.PORT }}
        POST_SERVER_ITEM_ACCESS_TOKEN: ${{ secrets.POST_SERVER_ITEM_ACCESS_TOKEN }}
